//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC3LP_ko.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC3LP_ko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   PengChat3 서버에 연결할수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_CannotConnectToServer {
            get {
                return ResourceManager.GetString("Str_CannotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_ConnectionInfo {
            get {
                return ResourceManager.GetString("Str_ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방 만들기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_CreateRoom {
            get {
                return ResourceManager.GetString("Str_CreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Delete {
            get {
                return ResourceManager.GetString("Str_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PengChat3 서버와의 연결이 끊어졌습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_DisconnectedServer {
            get {
                return ResourceManager.GetString("Str_DisconnectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 입력란을 채워주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_EmptyLabel {
            get {
                return ResourceManager.GetString("Str_EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_ID {
            get {
                return ResourceManager.GetString("Str_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림 창과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_InfoWindow {
            get {
                return ResourceManager.GetString("Str_InfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_IP {
            get {
                return ResourceManager.GetString("Str_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PengChat3 서버로부터 로그아웃 했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_LoggedOut {
            get {
                return ResourceManager.GetString("Str_LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Login {
            get {
                return ResourceManager.GetString("Str_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Logout {
            get {
                return ResourceManager.GetString("Str_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메인 화면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_MainPage {
            get {
                return ResourceManager.GetString("Str_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Master {
            get {
                return ResourceManager.GetString("Str_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 접속자 수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_MaxConnectorNum {
            get {
                return ResourceManager.GetString("Str_MaxConnectorNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필요없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_NoNeed {
            get {
                return ResourceManager.GetString("Str_NoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방이 선택되지 않았습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_NoSelectedRoom {
            get {
                return ResourceManager.GetString("Str_NoSelectedRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PengChat3 서버에 접속하지 못했습니다.
        ///아이디와 비밀번호를 확인하여 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_NotSuccessedConnect {
            get {
                return ResourceManager.GetString("Str_NotSuccessedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_PW {
            get {
                return ResourceManager.GetString("Str_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_RoomInfo {
            get {
                return ResourceManager.GetString("Str_RoomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_RoomName {
            get {
                return ResourceManager.GetString("Str_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Signin {
            get {
                return ResourceManager.GetString("Str_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PengChat3 서버에 접속하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_SuccessedConnect {
            get {
                return ResourceManager.GetString("Str_SuccessedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무제한과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Str_Unlimited {
            get {
                return ResourceManager.GetString("Str_Unlimited", resourceCulture);
            }
        }
    }
}
