//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC3LP_ko.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC3LP_ko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 권한이 없습니다..
        /// </summary>
        internal static string Str_AccessDenied {
            get {
                return ResourceManager.GetString("Str_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 님께서 들어오셨습니다..
        /// </summary>
        internal static string Str_AddClient {
            get {
                return ResourceManager.GetString("Str_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 같은 닉네임으로 접속해있습니다..
        /// </summary>
        internal static string Str_AlreadyLogged {
            get {
                return ResourceManager.GetString("Str_AlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정말로 방에서 나가시겠습니까?.
        /// </summary>
        internal static string Str_AreYouSureExit {
            get {
                return ResourceManager.GetString("Str_AreYouSureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메인 화면은 종료할수 없습니다!.
        /// </summary>
        internal static string Str_CannotCloseMainTab {
            get {
                return ResourceManager.GetString("Str_CannotCloseMainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PengChat3 서버에 연결할수 없습니다.
        /// </summary>
        internal static string Str_CannotConnectToServer {
            get {
                return ResourceManager.GetString("Str_CannotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방에 입장하실수 없습니다..
        /// </summary>
        internal static string Str_CannotEntryToRoom {
            get {
                return ResourceManager.GetString("Str_CannotEntryToRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연결 정보.
        /// </summary>
        internal static string Str_ConnectionInfo {
            get {
                return ResourceManager.GetString("Str_ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방 만들기.
        /// </summary>
        internal static string Str_CreateRoom {
            get {
                return ResourceManager.GetString("Str_CreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        internal static string Str_Delete {
            get {
                return ResourceManager.GetString("Str_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PengChat3 서버와의 연결이 끊어졌습니다..
        /// </summary>
        internal static string Str_DisconnectedServer {
            get {
                return ResourceManager.GetString("Str_DisconnectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모든 입력란을 채워주세요.
        /// </summary>
        internal static string Str_EmptyLabel {
            get {
                return ResourceManager.GetString("Str_EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 나가기.
        /// </summary>
        internal static string Str_Exit {
            get {
                return ResourceManager.GetString("Str_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방 만들기에 실패했습니다..
        /// </summary>
        internal static string Str_FailedToCreateRoom {
            get {
                return ResourceManager.GetString("Str_FailedToCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방 삭제에 실패했습니다..
        /// </summary>
        internal static string Str_FailedToDeleteRoom {
            get {
                return ResourceManager.GetString("Str_FailedToDeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일.
        /// </summary>
        internal static string Str_File {
            get {
                return ResourceManager.GetString("Str_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디.
        /// </summary>
        internal static string Str_ID {
            get {
                return ResourceManager.GetString("Str_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림 창.
        /// </summary>
        internal static string Str_InfoWindow {
            get {
                return ResourceManager.GetString("Str_InfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버주소.
        /// </summary>
        internal static string Str_IP {
            get {
                return ResourceManager.GetString("Str_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PengChat3 서버로부터 로그아웃 했습니다..
        /// </summary>
        internal static string Str_LoggedOut {
            get {
                return ResourceManager.GetString("Str_LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인.
        /// </summary>
        internal static string Str_Login {
            get {
                return ResourceManager.GetString("Str_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그아웃.
        /// </summary>
        internal static string Str_Logout {
            get {
                return ResourceManager.GetString("Str_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메인 화면.
        /// </summary>
        internal static string Str_MainPage {
            get {
                return ResourceManager.GetString("Str_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방장.
        /// </summary>
        internal static string Str_Master {
            get {
                return ResourceManager.GetString("Str_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대 접속자 수.
        /// </summary>
        internal static string Str_MaxConnectorNum {
            get {
                return ResourceManager.GetString("Str_MaxConnectorNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필요없음.
        /// </summary>
        internal static string Str_NoNeed {
            get {
                return ResourceManager.GetString("Str_NoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방이 선택되지 않았습니다.
        /// </summary>
        internal static string Str_NoSelectedRoom {
            get {
                return ResourceManager.GetString("Str_NoSelectedRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PengChat3 서버에 접속하지 못했습니다..
        /// </summary>
        internal static string Str_NotSuccessedConnect {
            get {
                return ResourceManager.GetString("Str_NotSuccessedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잘못된 비밀번호 입니다..
        /// </summary>
        internal static string Str_PasswordIsWrong {
            get {
                return ResourceManager.GetString("Str_PasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호.
        /// </summary>
        internal static string Str_PW {
            get {
                return ResourceManager.GetString("Str_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 님께서 퇴장하셨습니다..
        /// </summary>
        internal static string Str_RemoveClient {
            get {
                return ResourceManager.GetString("Str_RemoveClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방 정보.
        /// </summary>
        internal static string Str_RoomInfo {
            get {
                return ResourceManager.GetString("Str_RoomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방이 만원입니다..
        /// </summary>
        internal static string Str_RoomIsFull {
            get {
                return ResourceManager.GetString("Str_RoomIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방제.
        /// </summary>
        internal static string Str_RoomName {
            get {
                return ResourceManager.GetString("Str_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 같은 이름을 가진 방이 있습니다..
        /// </summary>
        internal static string Str_RoomNameOverlap {
            get {
                return ResourceManager.GetString("Str_RoomNameOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그런 방 ID는 존재하지 않습니다..
        /// </summary>
        internal static string Str_RoomNotExist {
            get {
                return ResourceManager.GetString("Str_RoomNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입장.
        /// </summary>
        internal static string Str_Signin {
            get {
                return ResourceManager.GetString("Str_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PengChat3 서버에 접속하였습니다..
        /// </summary>
        internal static string Str_SuccessedConnect {
            get {
                return ResourceManager.GetString("Str_SuccessedConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방을 성공적으로 만들었습니다..
        /// </summary>
        internal static string Str_SuccessedToCreateRoom {
            get {
                return ResourceManager.GetString("Str_SuccessedToCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방을 성공적으로 삭제했습니다..
        /// </summary>
        internal static string Str_SuccessedToDeleteRoom {
            get {
                return ResourceManager.GetString("Str_SuccessedToDeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 탭 종료.
        /// </summary>
        internal static string Str_TabClose {
            get {
                return ResourceManager.GetString("Str_TabClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대 접속자 수가 정확하지 않습니다..
        /// </summary>
        internal static string Str_UnknownCapacity {
            get {
                return ResourceManager.GetString("Str_UnknownCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 방 ID가 잘못되었습니다.
        /// </summary>
        internal static string Str_UnknownRoomID {
            get {
                return ResourceManager.GetString("Str_UnknownRoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 무제한.
        /// </summary>
        internal static string Str_Unlimited {
            get {
                return ResourceManager.GetString("Str_Unlimited", resourceCulture);
            }
        }
    }
}
